twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    # config/packages/twig.yaml
    form_themes: ['bootstrap_5_layout.html.twig']
=======
    form_themes: ['bootstrap_5_layout.html.twig']

>>>>>>> karim
when@test:
    twig:
        strict_variables: true
